### ISSUE TITLE
How to compile correctly?

### ISSUE THREAD

**Issue by John10v10** [AerialX/rawksd#1]
Hi AerialX,

I have been trying to compile this code on windows, but I had no luck.

There are countless issues I've had, and I had to go in and manually edit some of the code many times to get it even closer to a successful build.

I could only figure out the required DevkitPro libraries through trial and error (as in receiving compiler errors that the header files weren't found)
I've had to modify several declaration types to avoid -fpermissive errors.
I've had to include #include <sys/param.h> in many c files

and now I am completely stuck and hopeless on how to solve these errors:

when I attempt to compile filemodule.elf, I end up with an unresolved reference to "`__end__`" as shown here:
```
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/8.1.0/../../../../arm-none-eabi/lib/thumb/be\libsysbase.a(sbrk.o): In function `_sbrk_r':
(.text._sbrk_r+0x50): error: undefined reference to `__end__'
```

I installed MinGW just so I could compile stripios, and when I get it compiled, I end up with this issue in an attempt to run the exe.
![image](https://user-images.githubusercontent.com/16232480/105301573-b543e800-5b80-11eb-951f-2cb0f036aac7.png)

So... yeah.

I want to suggest that for people such as myself who want to compile this special open-source for Riivolution that you generously provided (which I thank you a lot for), I want to ask if you can provide good instructions for how we can compile it.

Thanks,
 - John10v10

**Comment by AerialX** [comment]
Sorry it took so long for me to get around to this. Though I've only tested and built on Linux, the link errors you've mentioned (related to sbrk and `__end__`) have been fixed.

I'm afraid I can't help much with building stripios on windows though; that error suggests you don't have a working C++ compiler (or at least something is wrong with libstdc++?)
